[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "AtomicThreading"
version = "0.1.0"
description = "A high-performance thread-safe data structure library for Python 3.13+ no-GIL."
readme = "README.md"
requires-python = ">=3.13"
license = { file = "LICENSE" } # MIT
authors = [
    { name="Mark Geleta", email="your@email.com" }
]
keywords = ["concurrent", "thread-safe", "no-GIL", "parallel", "atomic", "free-threading", "high-performance"]
classifiers = [
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.urls]
"Homepage" = "https://github.com/Synaptic724/AtomicThreading"
"Bug Tracker" = "https://github.com/Synaptic724/AtomicThreading/issues"
